#!/bin/bash

# This script creates proxy videos for editing. It processes all .MOV files in
# the current directory, scales them to 1080p based on their orientation
# (horizontal or vertical) and encodes the using the ProRes codec.
#
# Usage
#
#   ./gen_proxy.sh
#
#   The converted files will be saved in the 'proxy' directory.

shopt -s nullglob
AUDIO_CODEC_PCM_S16="pcm_s16le"
OUT_DIR="proxy"
FORMAT="MOV"
AUDIO_CODEC=$AUDIO_CODEC_PCM_S16
VIDEO_CODEC="prores_ks"
VIDEO_OPTIONS="-profile:v 0"
WATERMARK_PNG="$OUT_DIR/watermark.png"

source "$(dirname "$0")/utils.sh"

files=(*."${FORMAT}")
total=${#files[@]}

if [[ $total -eq 0 ]]; then
	echo "Error: No files found with format '${FORMAT}'"
	exit 1
fi

i=1
mkdir -p "${OUT_DIR}"

ffmpeg -nostdin -y -f lavfi -i "color=c=white@0:s=400x130,format=rgba" -vf "
  drawtext=text='Proxy':fontcolor=darkgray@0.5:fontsize=55:x=10:y=10,
  drawtext=text='1080p, prores':fontcolor=darkgray@0.5:fontsize=55:x=10:y=70,
  format=rgba
" -frames:v 1 -update 1 "$WATERMARK_PNG"

for input_file in "${files[@]}"; do
	echo "${input_file} ${i}/${total}"
	random_string=$(gen_random_string)
	out_file_tmp="${OUT_DIR}/${input_file}${random_string}.tmp.${FORMAT}"
	out_file="${OUT_DIR}/${input_file}"

	DIMENSIONS=$(ffprobe -v error -show_entries stream=width,height -of csv=p=0 "$input_file")
	WIDTH=$(echo "$DIMENSIONS" | cut -d ',' -f 1)
	HEIGHT=$(echo "$DIMENSIONS" | cut -d ',' -f 2)

	if [ "$WIDTH" -ge "$HEIGHT" ]; then
		SCALE="scale=1920:-2"
	else
		SCALE="scale=-2:1920"
	fi

	if ! ffmpeg \
		-nostdin \
		-y \
		-hwaccel auto \
		-i "${input_file}" \
		-i "$WATERMARK_PNG" \
		-filter_complex "
    [0:v]${SCALE}[scaled];
    [scaled][1:v]overlay=50:main_h-overlay_h-10:format=auto,
    format=yuv422p10le
  " \
		-c:v ${VIDEO_CODEC} \
		${VIDEO_OPTIONS} \
		-c:a ${AUDIO_CODEC} \
		-map_metadata 0 \
		-loglevel info \
		"${out_file_tmp}"; then
		echo "Error: ffmpeg failed"
		exit 1
	fi

	mv "${out_file_tmp}" "${out_file}"
	((i++))
done

rm $WATERMARK_PNG
